/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as TeamAgentIdRouteImport } from './routes/team.$agentId'
import { Route as SoldListingIdRouteImport } from './routes/sold.$listingId'
import { Route as SellAppraisalRouteImport } from './routes/sell.appraisal'
import { Route as RentListingIdRouteImport } from './routes/rent.$listingId'
import { Route as BuyListingIdRouteImport } from './routes/buy.$listingId'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAgentIdRoute = TeamAgentIdRouteImport.update({
  id: '/team/$agentId',
  path: '/team/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldListingIdRoute = SoldListingIdRouteImport.update({
  id: '/sold/$listingId',
  path: '/sold/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellAppraisalRoute = SellAppraisalRouteImport.update({
  id: '/appraisal',
  path: '/appraisal',
  getParentRoute: () => SellRoute,
} as any)
const RentListingIdRoute = RentListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => RentRoute,
} as any)
const BuyListingIdRoute = BuyListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => BuyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sell': typeof SellRouteWithChildren
  '/buy/$listingId': typeof BuyListingIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/sell/appraisal': typeof SellAppraisalRoute
  '/sold/$listingId': typeof SoldListingIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
  '/buy/': typeof BuyIndexRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sell': typeof SellRouteWithChildren
  '/buy/$listingId': typeof BuyListingIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/sell/appraisal': typeof SellAppraisalRoute
  '/sold/$listingId': typeof SoldListingIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
  '/buy': typeof BuyIndexRoute
  '/rent': typeof RentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sell': typeof SellRouteWithChildren
  '/buy/$listingId': typeof BuyListingIdRoute
  '/rent/$listingId': typeof RentListingIdRoute
  '/sell/appraisal': typeof SellAppraisalRoute
  '/sold/$listingId': typeof SoldListingIdRoute
  '/team/$agentId': typeof TeamAgentIdRoute
  '/buy/': typeof BuyIndexRoute
  '/rent/': typeof RentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sell'
    | '/buy/$listingId'
    | '/rent/$listingId'
    | '/sell/appraisal'
    | '/sold/$listingId'
    | '/team/$agentId'
    | '/buy/'
    | '/rent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sell'
    | '/buy/$listingId'
    | '/rent/$listingId'
    | '/sell/appraisal'
    | '/sold/$listingId'
    | '/team/$agentId'
    | '/buy'
    | '/rent'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sell'
    | '/buy/$listingId'
    | '/rent/$listingId'
    | '/sell/appraisal'
    | '/sold/$listingId'
    | '/team/$agentId'
    | '/buy/'
    | '/rent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SellRoute: typeof SellRouteWithChildren
  SoldListingIdRoute: typeof SoldListingIdRoute
  TeamAgentIdRoute: typeof TeamAgentIdRoute
  BuyIndexRoute: typeof BuyIndexRoute
  RentIndexRoute: typeof RentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$agentId': {
      id: '/team/$agentId'
      path: '/team/$agentId'
      fullPath: '/team/$agentId'
      preLoaderRoute: typeof TeamAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold/$listingId': {
      id: '/sold/$listingId'
      path: '/sold/$listingId'
      fullPath: '/sold/$listingId'
      preLoaderRoute: typeof SoldListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/appraisal': {
      id: '/sell/appraisal'
      path: '/appraisal'
      fullPath: '/sell/appraisal'
      preLoaderRoute: typeof SellAppraisalRouteImport
      parentRoute: typeof SellRoute
    }
    '/rent/$listingId': {
      id: '/rent/$listingId'
      path: '/$listingId'
      fullPath: '/rent/$listingId'
      preLoaderRoute: typeof RentListingIdRouteImport
      parentRoute: typeof RentRoute
    }
    '/buy/$listingId': {
      id: '/buy/$listingId'
      path: '/$listingId'
      fullPath: '/buy/$listingId'
      preLoaderRoute: typeof BuyListingIdRouteImport
      parentRoute: typeof BuyRoute
    }
  }
}

interface SellRouteChildren {
  SellAppraisalRoute: typeof SellAppraisalRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellAppraisalRoute: SellAppraisalRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SellRoute: SellRouteWithChildren,
  SoldListingIdRoute: SoldListingIdRoute,
  TeamAgentIdRoute: TeamAgentIdRoute,
  BuyIndexRoute: BuyIndexRoute,
  RentIndexRoute: RentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
